### PR TITLE
Auctions/English Auction

### PR DESCRIPTION
**Pull request by Saketd3769**
Added English Auction file with readme in Auction Directory.
By- Saket Dhakar, Anshit Arya, Prashant

### CODE REVIEW

**Comment by Saketd3769** [comment]
Added English Auction file with readme in Auction Directory.

**Comment by AthaSSiN** [comment]
Move it to Auctions/English_Auction folder

**Comment by Saketd3769** [comment]
Changed the directory name

**Comment by AthaSSiN** [comment]
Add the files inside an English_Auction folder within the Auctions folder, currently it's directly inside the Auctions folder

**Comment by Saketd3769** [comment]
Did the required changes

**Pull request merged**
