### PR TITLE
FPTP VOTING MECHANISM

### PR DESCRIPTION
**Pull request by Aadeesh74**
I Aadeesh Jain and Nikhesh worked on this fptp mechanism

### CODE REVIEW

**Comment by AthaSSiN** [comment]
Code quality is decent. Although lines 52-55 of the contract seem to be misaligned, correct that.
Decent README, just add links to your Github profiles at the end of the README in a section titles "Contributors"

**Review by Aadeesh74 — COMMENTED** [review]
did the required corrections and edits

**Comment by AthaSSiN** [comment]
Sorry I missed it yesterday, but the directory structure is incorrect. Move the code to Voting/FPTP directory.

**Review by Aadeesh74 — COMMENTED** [review]
Changed the directory

**Pull request merged**
